import "./globals.css"
import Nav from "@/components/Nav";

export const metadata = {
  title: "OPYE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <div className="main">
        <div className="bg" />
      </div>
      <div className="app">
        <Nav />
        {children}
      </div>

      </body>
    </html>
  );
}
